export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const NEW_NOMINATION_REQUEST = "NEW_NOMINATION_REQUEST";
export const NEW_NOMINATION_SUCCESS = "NEW_NOMINATION_SUCCESS";
export const NEW_NOMINATION_FAIL = "NEW_NOMINATION_FAIL";

export const NOMINATION_LIST_REQUEST = "NOMINATION_LIST_REQUEST";
export const NOMINATION_LIST_SUCCESS = "NOMINATION_LIST_SUCCESS";
export const NOMINATION_LIST_FAIL = "NOMINATION_LIST_FAIL";
export const NOMINATION_LIST_RESET = "NOMINATION_LIST_RESET";

export const NOMINATION_DETAILS_REQUEST = "NOMINATION_DETAILS_REQUEST";
export const NOMINATION_DETAILS_SUCCESS = "NOMINATION_DETAILS_SUCCESS";
export const NOMINATION_DETAILS_FAIL = "NOMINATION_DETAILS_FAIL";

export const NOMINAIION_DELETE_REQUEST = "NOMINAIION_DELETE_REQUEST";
export const NOMINAIION_DELETE_SUCCESS = "NOMINAIION_DELETE_SUCCESS";
export const NOMINAIION_DELETE_FAIL = "NOMINAIION_DELETE_FAIL";


export const VOTE_LIST_REQUEST = "VOTE_LIST_REQUEST";
export const VOTE_LIST_SUCCESS = "VOTE_LIST_SUCCESS";
export const VOTE_LIST_FAIL = "VOTE_LIST_FAIL";

export const VOTE_DETAILS_REQUEST = "VOTE_DETAILS_REQUEST";
export const VOTE_DETAILS_SUCCESS = "VOTE_DETAILS_SUCCESS";
export const VOTE_DETAILS_FAIL = "VOTE_DETAILS_FAIL";


export const USER_CONTACT_LIST_REQUEST = "USER_CONTACT_LIST_REQUEST";
export const USER_CONTACT_LIST_SUCCESS = "USER_CONTACT_LIST_SUCCESS";
export const USER_CONTACT_LIST_FAIL = "USER_CONTACT_LIST_FAIL";


export const USER_CONTACT_DETAILS_REQUEST = "USER_CONTACT_DETAILS_REQUEST";
export const USER_CONTACT_DETAILS_SUCCESS = "USER_CONTACT_DETAILS_SUCCESS";
export const USER_CONTACT_DETAILS_FAIL = "USER_CONTACT_DETAILS_FAIL";


export const USER_CONTACT_DELETE_REQUEST = "USER_CONTACT_DELETE_REQUEST";
export const USER_CONTACT_DELETE_SUCCESS = "USER_CONTACT_DELETE_SUCCESS";
export const USER_CONTACT_DELETE_FAIL = "USER_CONTACT_DELETE_FAIL";



export const ADMIN_LIST_REQUEST = "ADMIN_LIST_REQUEST";
export const ADMIN_LIST_SUCCESS = "ADMIN_LIST_SUCCESS";
export const ADMIN_LIST_FAIL = "ADMIN_LIST_FAIL";

export const ADMIN_DETAILS_REQUEST = "ADMIN_DETAILS_REQUEST";
export const ADMIN_DETAILS_SUCCESS = "ADMIN_DETAILS_SUCCESS";
export const ADMIN_DETAILS_FAIL = "ADMIN_DETAILS_FAIL";