export const AUTH_LOADED_REQUEST = "AUTH_LOADED_REQUEST";
export const AUTH_LOADED_SUCCESS = "AUTH_LOADED_SUCCESS";
export const AUTH_LOADED_FAIL = "AUTH_LOADED_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"; 
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"; 
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";


export const USER_GENERATE_OTP_REQUEST = "USER_GENERATE_OTP_REQUEST";
export const USER_GENERATE_OTP_SUCCESS = "USER_GENERATE_OTP_SUCCESS";
export const USER_GENERATE_OTP_FAIL = "USER_GENERATE_OTP_FAIL";

export const USER_VERIFY_OTP_REQUEST = "USER_VERIFY_OTP_REQUEST";
export const USER_VERIFY_OTP_SUCCESS = "USER_VERIFY_OTP_SUCCESS";
export const USER_VERIFY_OTP_FAIL = "USER_VERIFY_OTP_FAIL";

export const LOGOUT = "LOGOUT"; 

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"; 
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"; 
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"; 
